/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import br.com.DAO.OrcamentoDAO;
import br.com.Model.ModelOrcamento;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Medeiros
 */
public class ListaOrcamentos extends javax.swing.JFrame {

    ModelOrcamento mO = new ModelOrcamento();
    OrcamentoDAO odao = new OrcamentoDAO();
    int codigo;
    Orcamento o = new Orcamento();

    public void pesquisaOrcamentos() {
        DefaultTableModel tabelaOrcamentos = (DefaultTableModel) jTableListaOrcamentos.getModel();
        try {
            tabelaOrcamentos.setNumRows(0);
            for (ModelOrcamento mO : odao.pesquisarOrcamentos(jTextFieldPesquisa.getText())) {
                tabelaOrcamentos.addRow(new Object[]{
                    mO.getCod_orcamento(),
                    mO.getCliente(),
                    mO.getDataOrcamento()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void setaOrcamentos() {
        DefaultTableModel tabelaOrcamentos = (DefaultTableModel) o.jTableGeral.getModel();
        try {
            tabelaOrcamentos.setNumRows(0);
            for (ModelOrcamento mO : odao.pesquisarOrcamentos(mO.getCod_orcamento())) {
                tabelaOrcamentos.addRow(new Object[]{
                    mO.getCod_barras(),
                    mO.getDescricao(),
                    mO.getValor_unidade(),
                    mO.getQtde(),
                    mO.getValorPPeca()

                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public ListaOrcamentos() {
        initComponents();
        setIconImage(new ImageIcon("Img/caloriv2.png").getImage());
        setTitle("ERP - CaloriCar - Autopecas ");
        pesquisaOrcamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaOrcamentos = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Selecione o orçamento que deseja visualizar ou pesquise..");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableListaOrcamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Cliente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaOrcamentos.getTableHeader().setReorderingAllowed(false);
        jTableListaOrcamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaOrcamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaOrcamentos);
        if (jTableListaOrcamentos.getColumnModel().getColumnCount() > 0) {
            jTableListaOrcamentos.getColumnModel().getColumn(0).setResizable(false);
            jTableListaOrcamentos.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableListaOrcamentos.getColumnModel().getColumn(1).setResizable(false);
            jTableListaOrcamentos.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableListaOrcamentos.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyReleased(evt);
            }
        });

        jButton1.setText("Excluir Orcamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldPesquisa)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(420, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyReleased
        pesquisaOrcamentos();
    }//GEN-LAST:event_jTextFieldPesquisaKeyReleased

    private void jTableListaOrcamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaOrcamentosMouseClicked
        int setar = jTableListaOrcamentos.getSelectedRow();
        mO.setCod_orcamento(Integer.parseInt(jTableListaOrcamentos.getModel().getValueAt(setar, 0).toString()));
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja visualizar este orçamento?");
        if (escolha == JOptionPane.YES_OPTION) {
            odao.pesquisaInfo(mO);
            o.carregacod = false;
            o.jFormattedTextFieldDataOrcamento.setText(mO.getDataOrcamento());
            o.codOrcamento = mO.getCod_orcamento();
            o.jTextFieldNomeCliente.setText(mO.getCliente());
            o.jFormattedTextFieldTelefoneFixo.setText(mO.getTelefone());
            o.jFormattedTextFieldCelular.setText(mO.getCelular());
            o.jLabelValorTotal.setText(new DecimalFormat("R$ #,##0.00").format(mO.getValor_total()));
            setaOrcamentos();
            this.dispose();
            o.setVisible(true);
        }
    }//GEN-LAST:event_jTableListaOrcamentosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Deseja excluir o orcamento selecionado?");
        if (escolha == JOptionPane.YES_OPTION) {
            odao.apagaOrcameto(mO);
            this.dispose();
            new ListaOrcamentos().setVisible(true);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaOrcamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableListaOrcamentos;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
