/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.View;

import br.com.DAO.EstoqueDAO;
import br.com.Model.ModelEntrada;
import br.com.Model.ModelEstoque;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael Medeiros
 */
public class PesquisarEstoque extends javax.swing.JFrame {

    EstoqueDAO edao = new EstoqueDAO();
    ModelEstoque mE = new ModelEstoque();
    String codigo;
    private EntradaEstoque eE;
    ModelEntrada mEE = new ModelEntrada();
    
             
    

     
		
    

  

    public void pesquisaEstoque_Descricao() {
        DefaultTableModel tabelaEstoque = (DefaultTableModel) jTableEstoque.getModel();
        try {
            tabelaEstoque.setNumRows(0);
            for (ModelEstoque mE : edao.pesquisarEstoque(jTextFieldPesquisa.getText())) {
                tabelaEstoque.addRow(new Object[]{
                    mE.getCod_barras(),
                    mE.getDescricao(),
                    mE.getCategoria(),
                    mE.getFornecedor(),
                    mE.getPreco_custo(),
                    mE.getPreco_venda(),
                    mE.getLucro_unidade(),
                    mE.getQuantidade(),
                    mE.getAlerta_estoque(),
                    mE.getStatus_estoque()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void pesquisaEstoque_CodBarras() {
        DefaultTableModel tabelaEstoque = (DefaultTableModel) jTableEstoque.getModel();
        try {
            tabelaEstoque.setNumRows(0);
            for (ModelEstoque mE : edao.pesquisarEstoque_CodBarras(jTextFieldPesquisa.getText())) {
                tabelaEstoque.addRow(new Object[]{
                    mE.getCod_barras(),
                    mE.getDescricao(),
                    mE.getCategoria(),
                    mE.getFornecedor(),
                    mE.getPreco_custo(),
                    mE.getPreco_venda(),
                    mE.getLucro_unidade(),
                    mE.getQuantidade(),
                    mE.getAlerta_estoque(),
                    mE.getStatus_estoque()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public PesquisarEstoque() {
        initComponents();
        this.eE = new EntradaEstoque(this, true);
        pesquisaEstoque_Descricao();
        setIconImage(new ImageIcon("Img/caloriv2.png").getImage());
        setTitle("ERP - CaloriCar - Autopecas ");
        jRadioButtonDescricao.setSelected(true);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonCodBarra = new javax.swing.JRadioButton();
        jRadioButtonDescricao = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstoque = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Consultar Estoque");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Filtrar por:");

        buttonGroup1.add(jRadioButtonCodBarra);
        jRadioButtonCodBarra.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonCodBarra.setText("Código de Barras");

        buttonGroup1.add(jRadioButtonDescricao);
        jRadioButtonDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButtonDescricao.setText("Descrição");

        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Categoria", "Fornecedor", "Preço Custo", "Preço Venda", "Lucro Unidade", "Quantidade", "QtdeAlerta", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEstoque.setToolTipText(jTableEstoque.getName());
        jTableEstoque.getTableHeader().setReorderingAllowed(false);
        jTableEstoque.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTableEstoqueMouseMoved(evt);
            }
        });
        jTableEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstoqueMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTableEstoqueMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstoque);
        if (jTableEstoque.getColumnModel().getColumnCount() > 0) {
            jTableEstoque.getColumnModel().getColumn(0).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableEstoque.getColumnModel().getColumn(1).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableEstoque.getColumnModel().getColumn(2).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTableEstoque.getColumnModel().getColumn(3).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTableEstoque.getColumnModel().getColumn(4).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(4).setPreferredWidth(5);
            jTableEstoque.getColumnModel().getColumn(5).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(5).setPreferredWidth(5);
            jTableEstoque.getColumnModel().getColumn(6).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(6).setPreferredWidth(5);
            jTableEstoque.getColumnModel().getColumn(7).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(7).setPreferredWidth(10);
            jTableEstoque.getColumnModel().getColumn(8).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(8).setPreferredWidth(5);
            jTableEstoque.getColumnModel().getColumn(9).setResizable(false);
            jTableEstoque.getColumnModel().getColumn(9).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Efetuar Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Controle de Estoque:");

        jLabel4.setText("Altereção no valor ou descrição, clicar sobre o mesmo");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Novo Produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE..", "AlertaLimite", "EmEstoque", "ESGOTADO" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)))
                        .addGap(0, 642, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jMenu1.setText("Atalhos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem1.setText("Atualizar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(jRadioButtonCodBarra)
                        .addGap(0, 0, 0)
                        .addComponent(jRadioButtonDescricao))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPesquisa))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2))
                    .addComponent(jRadioButtonCodBarra)
                    .addComponent(jRadioButtonDescricao))
                .addGap(2, 2, 2)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(960, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyReleased
        if (jRadioButtonDescricao.isSelected()) {
            pesquisaEstoque_Descricao();
        } else {
            if (jRadioButtonCodBarra.isSelected()) {
                pesquisaEstoque_CodBarras();
            }
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyReleased

    private void jTableEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstoqueMouseClicked
         if (evt.getButton() == MouseEvent.BUTTON3) {
          int setar = jTableEstoque.getSelectedRow();
          JOptionPane.showMessageDialog(null, jTableEstoque.getModel().getValueAt(setar, 1).toString());
         
         } else {
        int setar = jTableEstoque.getSelectedRow();
        codigo = (jTableEstoque.getModel().getValueAt(setar, 0).toString());

        int escolha = JOptionPane.showConfirmDialog(null, "Visualizar ficha completa? ", "Informações", JOptionPane.YES_NO_OPTION);
        if (escolha == JOptionPane.YES_OPTION) {

            mE.setCod_barras(codigo);
            edao.pesquisaInfoEstoque(mE);
            CadastroDeEstoque cE = new CadastroDeEstoque();
            cE.jTextFieldDescricaoProduto.setText(mE.getDescricao());
            cE.jTextFieldCodBarras.setText(mE.getCod_barras());
            cE.jTextFieldPrecoVenda.setText(String.valueOf(mE.getPreco_venda()));
            cE.jTextFieldPrecoCusto.setText(String.valueOf(mE.getPreco_custo()));
            cE.jTextFieldLucroUnidade.setText(String.valueOf(mE.getLucro_unidade()));
            cE.jComboBoxCategoria.setSelectedItem(String.valueOf(mE.getCategoria()));
            cE.jComboBoxFornecedor.setSelectedItem(String.valueOf(mE.getFornecedor()));
            cE.jTextFieldAlertaEstoque.setText(String.valueOf(mE.getAlerta_estoque()));
            cE.jTextFieldGetFornecedor.setText(mE.getFornecedor());
            cE.setVisible(true);
        } else {

        }
         }
    }//GEN-LAST:event_jTableEstoqueMouseClicked
    


    
    
              
	
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CadastroDeEstoque cE = new CadastroDeEstoque();
        cE.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        new PesquisarEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int escolha = JOptionPane.showConfirmDialog(null, "Realizar Entrada? ", "Informações", JOptionPane.YES_NO_OPTION);
        if (escolha == JOptionPane.YES_OPTION) {
            mE.setCod_barras(codigo);
            edao.pesquisaInfoEstoque(mE);
            eE.jTextFieldCodBarras.setText(mE.getCod_barras());
            eE.jTextFieldDescricao.setText(mE.getDescricao());
            eE.jTextFieldFornecedor.setText(mE.getFornecedor());
            eE.jTextFieldQtdeAtual.setText(String.valueOf(mE.getQuantidade()));
            mEE.setCod_barras(codigo);
            edao.pesquisaEntradas(mEE);
            eE.jTextFieldUltimaEntrada.setText(mEE.getUltima_entrada());
            this.dispose();
            eE.setVisible(true);
        } else {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

        DefaultTableModel tabelaEstoque = (DefaultTableModel) jTableEstoque.getModel();
        try {
            tabelaEstoque.setNumRows(0);
            for (ModelEstoque mE : edao.pesquisarEstoque_Status(String.valueOf(jComboBox1.getSelectedItem()))) {
                tabelaEstoque.addRow(new Object[]{
                    mE.getCod_barras(),
                    mE.getDescricao(),
                    mE.getCategoria(),
                    mE.getFornecedor(),
                    mE.getPreco_custo(),
                    mE.getPreco_venda(),
                    mE.getLucro_unidade(),
                    mE.getQuantidade(),
                    mE.getAlerta_estoque(),
                    mE.getStatus_estoque()
                });
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTableEstoqueMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstoqueMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableEstoqueMouseReleased
       
    private void jTableEstoqueMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstoqueMouseMoved
           int setar = jTableEstoque.getSelectedRow();
        String moved = (jTableEstoque.getModel().getValueAt(setar, 1).toString());
        jTableEstoque.setToolTipText(moved);
    }//GEN-LAST:event_jTableEstoqueMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonCodBarra;
    private javax.swing.JRadioButton jRadioButtonDescricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableEstoque;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
